- hosts: masters
  tasks:
  - name: copy podfile
    copy:
      src: /var/lib/jenkins/workspace/busybox/busybox.yaml
      dest: /busybox.yaml
  - name: Make busybox pod
    command: kubectl create -f /busybox.yml